export const chapters = [
  { chapterId: '01', file: 'Chapter 01 Functions and Models.md', label: '함수와 모델' },
  { chapterId: '02', file: 'Chapter 02 Limits and Derivatives.md', label: '극한과 도함수' },
  { chapterId: '03', file: 'Chapter 03 Differentiation Rules.md', label: '미분의 규칙' },
  { chapterId: '04', file: 'Chapter 04 Applications of Differentiation.md', label: '미분의 응용' },
  { chapterId: '05', file: 'Chapter 05 Integrals.md', label: '적분' },
  { chapterId: '07', file: 'Chapter 07 Techniques of Integration.md', label: '적분 기법' },
  { chapterId: '09', file: 'Chapter 09 Differential Equations.md', label: '미분 방정식' },
  { chapterId: '10', file: 'Chapter 10 Parametric Equations and Polar Coordinates.md', label: '매개변수 방정식과 극좌표' },
  { chapterId: '11', file: 'Chapter 11 Infinite Sequences and Series.md', label: '무한 수열과 급수' },
  { chapterId: '12', file: 'Chapter 12 Vectors and the Geometry of Space.md', label: '벡터와 공간의 기하학' },
  { chapterId: '13', file: 'Chapter 13 Vector Functions.md', label: '벡터 함수' },
  { chapterId: '14', file: 'Chapter 14 Partial Derivatives.md', label: '편미분' },
  { chapterId: '15', file: 'Chapter 15 Multiple Integrals.md', label: '다중 적분' },
  { chapterId: '16', file: 'Chapter 16 Vector Calculus.md', label: '벡터 미적분' },
  { chapterId: '17', file: 'Chapter 17 Second-Order Differential Equations.md', label: '2차 미분 방정식' },
];